set(_CATKIN_CURRENT_PACKAGE "robocup_home_education_los_ultramarinos")
set(robocup_home_education_los_ultramarinos_VERSION "0.0.0")
set(robocup_home_education_los_ultramarinos_MAINTAINER "lroa <lroa@todo.todo>")
set(robocup_home_education_los_ultramarinos_PACKAGE_FORMAT "2")
set(robocup_home_education_los_ultramarinos_BUILD_DEPENDS "std_msgs" "roscpp" "dialogflow_ros_msgs" "roslint" "sound_play" "actionlib_msgs" "message_generation")
set(robocup_home_education_los_ultramarinos_BUILD_EXPORT_DEPENDS )
set(robocup_home_education_los_ultramarinos_BUILDTOOL_DEPENDS "catkin")
set(robocup_home_education_los_ultramarinos_BUILDTOOL_EXPORT_DEPENDS )
set(robocup_home_education_los_ultramarinos_EXEC_DEPENDS "roscpp" "std_msgs" "dialogflow_ros_msgs" "sound_play" "actionlib_msgs" "message_runtime")
set(robocup_home_education_los_ultramarinos_RUN_DEPENDS "roscpp" "std_msgs" "dialogflow_ros_msgs" "sound_play" "actionlib_msgs" "message_runtime")
set(robocup_home_education_los_ultramarinos_TEST_DEPENDS )
set(robocup_home_education_los_ultramarinos_DOC_DEPENDS )
set(robocup_home_education_los_ultramarinos_URL_WEBSITE "")
set(robocup_home_education_los_ultramarinos_URL_BUGTRACKER "")
set(robocup_home_education_los_ultramarinos_URL_REPOSITORY "")
set(robocup_home_education_los_ultramarinos_DEPRECATED "")